#alias vol="pactl set-sink-volume 0"
alias eclipse="~/applications/eclipse/eclipse"
alias sl=ls
alias setup=~/scripts/setup/choose.sh
alias chrome=chromium-browser
alias LS=ls
alias clipoard="xclip -selection clipboard"
alias lock="gnome-screensaver-command -l"
alias ewa=~/scripts/bash/ewa.sh
alias pushAll=~/scripts/git/push_master_all_remotes.git
alias build_remote="~/dev/remote_compile/env/bin/python 
~/dev/remote_compile/remote_compile.py"

